#!/bin/bash

set -e

if [ -f "setup-project-here" ]; then
echo "Error: call this script from inside your project directory"
exit 1
fi

SOURCE=$(dirname "$(readlink -f "$0")")
TARGET=$(pwd)

cp -R $SOURCE/.junie $TARGET
cp -R $SOURCE/src $TARGET
cp -R $SOURCE/tests $TARGET
cp $SOURCE/.gitignore $TARGET
cp $SOURCE/template-composer.json $TARGET/composer.json
cp $SOURCE/phpstan.neon $TARGET
cp $SOURCE/phpunit.xml $TARGET
